### ISSUE TITLE
Tooltip on "Copy to Clipboard" only shows on click

### ISSUE THREAD

**Issue by tpenndorf** [trehn/teamvault#33]
Tooltip on "Copy to Clipboard" only shows on click and not on mouseover like on other buttons.

**Comment by trehn** [comment]
This is probably due to the flash applet being placed over the button. IIRC ZeroClipboard should propagate hover events, will have to investigate.

**Comment by trehn** [comment]
fixed in 0bac0789cd3188e8aee76cd97612896ba7d64ed3
