### ISSUE TITLE
Can't type in "share" form

### ISSUE THREAD

**Issue by vain** [trehn/teamvault#52]
* Open a secret, hit "share".
* Try to enter a user name or group. Notice that you can't type anything. :)

We were able to reproduce this on several browsers (Firefox, Chrome, Opera, ...).

**Comment by vain** [comment]
(Using git master, that is.)

**Comment by trehn** [comment]
can reproduce

**Comment by trehn** [comment]
note to self: https://github.com/trehn/teamvault/blob/master/src/teamvault/apps/secrets/templates/secrets/secret_detail.html#L384

will look into this tonight
