### ISSUE TITLE
Visibility of "username"

### ISSUE THREAD

**Issue by vain** [trehn/teamvault#55]
I know this has been discussed before :-), but I really do think that "username" should be visible by default in the "add" form. Here's why:

-   Storing username and password is the common case: In the database of my private password manager, there are 128 "passwords". However, 123 of those are actually "username + password". Only 5 items are just a password and no username. In our company's database, there are about 4000 passwords and only 19 of those lack a username.
-   If "username" is hidden, it's likely to confuse users.
-   The username is already visible in search results.

What do you think?

**Comment by mseibert** [comment]
+1

**Comment by mseibert** [comment]
Cool. :+1:
