### ISSUE TITLE
Request access dialog: Can't type fast

### ISSUE THREAD

**Issue by vain** [trehn/teamvault#58]
Each and every keystroke generates an HTTP request. When you type fast, a lot of characters are missing.

https://dump.uninformativ.de/volatile/Kabl-Tiss-17/tmpO8k7Xl.png

**Comment by trehn** [comment]
Cannot reproduce. It doesn't do these requests for me and I don't see why it ever would.

Something is very wrong.

**Comment by vain** [comment]
Yeah, this appears to have been fixed by the recent drop of jquery.hotkeys. Works fine with 0.4.3.

Sorry for the noise.
