### ISSUE TITLE
Request to delete an entry

### ISSUE THREAD

**Issue by mseibert** [trehn/teamvault#60]
Instead of a request to edit a request to delete may be a nice option.

**Comment by trehn** [comment]
Why the distinction? You can delete it after you have been granted access.

**Comment by mseibert** [comment]
1. I saw countless duplicates in our list. If I had requested access, I would have forgotten why I requested access as soon as it was granted.

2. In most cases I just think, that a password should be deleted. I want to flag it with a "deletion proposal". As soon as multiple people agree or see it, it is liklier that others will feel confident to actually delete it.

Just some thoughts. No need to act on it, if it's no priority.

**Comment by trehn** [comment]
Closing for now, not seeing this happening anytime soon.
