### ISSUE TITLE
How to register / request access

### ISSUE THREAD

**Issue by noqqe** [trehn/teamvault#67]
I cannot find how to request a new account as a normal User. Neither, webui, api or in the source. Normal root user was created through plumbing command. 

Whats the way the do that?

**Comment by trehn** [comment]
Currently the only "official" way is to use LDAP (the default config contains an example). If that's not an option for you, I guess this could work, but I haven't tested it:

```
# teamvault plumbing shell
>>> from django.contrib.auth.models import User
>>> User.objects.create_user(username="jdoe", email="jdoe@example.com", password="secret")
```

**Comment by tsfoer** [comment]
Your code snipet is working fine, thanks :)
