### ISSUE TITLE
Username (and possibly other fields) should be visible when reviewing access requests

### ISSUE THREAD

**Issue by vain** [trehn/teamvault#84]
Currently, when reviewing an access request, there's a link to the secret. Of course, when you click that link all info will be shown. It would be easier for users, though, if the username would be visible directly.

**Comment by mseibert** [comment]
Recently we had a problem, when a user applied for access to the wron element. During the process of approving the request I would not see, that it was inappropriate to approve it. So this usability problem turned into a business problem. I am all for changing this and making sure, that people have more confidence and transparency on what they apply and approve.
