### ISSUE TITLE
Enforce unambiguous font for password display

### ISSUE THREAD

**Issue by vain** [trehn/teamvault#85]
TeamVault currently uses “`monospace`” which might not be suitable for displaying passwords (depending on what fonts a client uses). You know, “`l`” vs. “`|`” vs. “`1`”, and so on.

How about using a webfont? [Ubuntu Mono](http://font.ubuntu.com/) looks pretty good in terms of ambiguity. 

If you want to *bundle* the font instead of using the version on the internet, I'll check if the license allows that.

**Comment by mseibert** [comment]
+1

**Comment by trehn** [comment]
Yes, we'd have to bundle the font. The only exception to that so far is Gravatar and I'm considering to remove that.
