### ISSUE TITLE
being owner of a secret doesn't make it visible for one

### ISSUE THREAD

**Issue by MaZderMind** [trehn/teamvault#95]
Being one of the owners of a secret or belonging to the owner-group of a secret does not make it visible. I can't see a useful situation for this and it is confusing (i created dozens of secrets, adding my group as owner, expecting them to be able to view the secret).

I propose this to be changed, so that owners can always see a secret they own, directly or indirectly.
![screenshot from 2017-05-20 21-11-17](https://cloud.githubusercontent.com/assets/142237/26278709/4cd506b0-3da1-11e7-9f87-57a06c35cf06.png)

**Comment by trehn** [comment]
owners have been removed and replaced with notification options

existing owners will be added to allowed users in migration
