### ISSUE TITLE
Ability to set ALLOWED_HOSTS independent of base_url

### ISSUE THREAD

**Issue by MaZderMind** [trehn/teamvault#97]
When operating TeamVault behind a http(s)-Proxy, `ALLOWED_HOSTS` needs to contain the internal ip/port (ie `http://127.0.0.1:8080`). Currently `ALLOWED_HOSTS` is only configured [based on base_url](https://github.com/trehn/teamvault/blob/2a34c76e644bb832c061d5b2f0bdc92ac6f584ae/src/teamvault/apps/settings/config.py#L16), so the base_url has to be set to `http://127.0.0.1:8080` which is obviously incorrect in a https-proxy-setup and will result to problems when the base_url is used for redirects.

It would be nice to be able to set / add to `ALLOWED_HOSTS` independent of the base_url.

**Comment by trehn** [comment]
No, you just need to configure your proxy to leave the Host header as it is. See the included nginx config for an example.

**Comment by MaZderMind** [comment]
Thank you for explaining.
