### ISSUE TITLE
Documentation about generated keys in teamvault.cfg is misleading

### ISSUE THREAD

**Issue by MaZderMind** [trehn/teamvault#98]
In `teamvault.cfg` [at multiple places the Config-File](https://github.com/trehn/teamvault/blob/master/teamvault.cfg#L4) documentation states _"This key has been generated for you, there is no need to change it"_. From the point of view of one installing TeamVault this is not true, as the keys are clearly coming from the git-repository.

I assume these texts were auto-generated from django and it is true that they were generated for *you* but the would have to be changed by any other user.

**Comment by trehn** [comment]
The teamvault.cfg you referenced is just a stray file I committed accidentally. The keys are generated during `teamvault setup`.
